# need the makefile to give an error if this doesn't exist
PROGS := cycles-per-sec.c 
PROGS += mode.c
PROGS += weird-result.c
PROGS += measure.c 

COMMON_SRC :=

# uncomment if you want it to automatically run.
# RUN=1

# define this if you need to give the device for your pi
TTYUSB = 
BOOTLOADER = pi-install
RUN = 1

include $(CS140E_2026_PATH)/libpi/mk/Makefile.robust-v2
