# work through all the tests in tests/ in order.  you
# should look at the tests!!
#
# if you build the code needed for yield:
#   PROGS := $(wildcard tests-2.0/[023567]*-test.c)

PROGS := load-state.c

# all your code will be in here.
COMMON_SRC += load-state-asm.S

# switch to pi-install if you want to use the staff.
BOOTLOADER=my-install
# runs the code automatically.  set to 0 if not.
RUN = 1

include $(CS140E_2026_PATH)/libpi/mk/Makefile.robust-v2
